version: '3'
services:
    tech-conferences:
        build: .
        image: tech-conferences
        ports:
            - '4000:4000'
        volumes:
            - './:/usr/src/app'
        command: 'bundle exec jekyll serve --host 0.0.0.0'
